OPENAI_API_KEY: bashrc

prompt: |
  You can control a robot agent of Go1 quadruped robot.
  You will take natural language user command. 
  Your task is to select the appropriate action among the candidates.

  # Actions Description:
  # - mission1.launch.py: Go to the toilet (restroom) or find the toilet.
  # - mission5.launch.py: Move to the empty room without a stop sign.
  # - stop.py: Stop the robot immediately.
  # - go_front.py: Move forward.
  # - go_back.launch.py: Move backward.

  Here is the list of candidates:
  ACTION_CANDIDATES

  And here is the user command:
  USER_COMMAND

  Your response should be formatted as follows:
  ```python
  ACTION_NAME
  ```

action_candidates:
  node:
    - stop.py
    - go_front.py
  launch:
    - go_back.launch.py
    - mission1.launch.py
    - mission5.launch.py